Подгрузил программу
Tanukyes/Dorozhkin_Danial_Dmitrirevich_ISM-114_Task_5 pull request #1
Opened 2021-10-08 07:39 UTC by Tanukyes

Функция выясняет, является ли год високосным. Високосность определяется следующим образом: если номер года не делится на 100, то високосным считается тот, который делится на 4 без остатка; если номер года делится на 100, то номер високосного года делится на 400 без остатка.

2021-10-13 09:38 UTC, MarinaPaley requested changes

2021-10-13 09:38 UTC, MarinaPaley commented on main.cpp
> +	if (year < 0 || cin.fail())
это вообще зачем и откуда?

2021-10-13 09:38 UTC, MarinaPaley commented on main.cpp
> +	return year % 400 == 0 || year % 100 != 0 && year % 4 == 0;
это нужно вынести  в отдельную функцию

2021-10-13 09:38 UTC, MarinaPaley commented on main.cpp
> +}
1. Зачем, кажется, что для проверки следует вводить один раз год, а потом вызывать ВСЕ функции в правильном порядке, чтобы ловить ошибку
2. Зачем писать, что год не високосный после того, как все же будет ошибка

2021-10-15 07:27 UTC, Tanukyes commented on main.cpp
> +	if (year < 0 || cin.fail())
Мы вводим  год с клавиатуры и проверяем корректность ввода

2021-10-15 07:29 UTC, Tanukyes commented on main.cpp
> +}
Нам нужно каждую функцию проверить по условию задания, поэтому для каждой мы и вводим свой год. Високосный или нет – это результат работы функции. А если год введен ошибочно, то информация об этом тоже выводится

2021-10-27 23:02 UTC, MarinaPaley requested changes

2021-10-27 23:02 UTC, MarinaPaley commented on main.cpp
> +	if (year < 0 || cin.fail())
мы НЕ должны вводить ничего с клавиатуры (из файла и т.д.)

2021-10-27 23:02 UTC, MarinaPaley commented on main.cpp
> +}
Да, выводится сначала ошибка, а потом радостно сообщение о том, что год не високосный), однако, такого года в Вашем мире НЕ СУЩЕСТВУЕТ! Это ошибка логики!

2021-10-27 23:02 UTC, MarinaPaley commented on main.cpp
> +	return year % 400 == 0 || year % 100 != 0 && year % 4 == 0;
я Вам в прошлый раз написала, что вычисление нужно вынести в отдельную функцию, а не копипастить 33 раза

2021-12-10 09:43 UTC, merged